---
# tasks file for storage
- name: package
  package:
    name: xfsprogs
  when:
    - storage_conf is search ("xfs")
  tags:
    - storage
    - package

- name: volume group
  lvg:
    vg: '{{ item.vg_name }}'
    pvs: '{{ item.pvs }}'
  loop: '{{ storage_conf }}'
  register: vg
  when:
    - item.pvs is defined
    - item.pvs | length > 0
  tags:
    - storage
    - vg

- name: logical volume
  lvol:
    pvs: '{{ item.pvs | default(omit) }}'
    vg: '{{ item.vg_name }}'
    lv: '{{ item.lv_name }}'
    size: '{{ item.lv_size }}'
  loop: '{{ storage_conf }}'
  register: lv
  when:
    - vg is succeeded
  tags:
    - storage
    - lv

- name: "filesystem"
  filesystem:
    dev: '/dev/mapper/{{ item.vg_name }}-{{ item.lv_name }}'
    fstype: '{{ item.fs_type }}'
    resizefs: true
  loop: '{{ storage_conf }}'
  register: fs
  ignore_errors: true
  when:
    - not ansible_check_mode
    - lv is changed
    - item.fs_type is defined
  tags:
    - storage
    - fs

- name: mount
  mount:
    path: '{{ item.fs_mountpoint }}'
    src: '/dev/mapper/{{ item.vg_name }}-{{ item.lv_name }}'
    fstype: '{{ item.fs_type }}'
    state: "{{ item.state | default('mounted') }}"
    opts: '{{ item.fs_mountoptions | default(omit) }}'
    dump: '{{ item.fs_dump | default(omit) }}'
    passno: '{{ item.fs_passno | default(omit) }}'
  loop: '{{ storage_conf }}'
  when:
    - item.fs_mountpoint is defined
    - item.fs_src is undefined
  notify: systemd reload
  tags:
    - storage
    - mount

- name: mount
  mount:
    path: '{{ item.fs_mountpoint }}'
    src: '{{ item.fs_src }}'
    fstype: '{{ item.fs_type }}'
    state: "{{ item.state | default('mounted') }}"
    opts: '{{ item.fs_mountoptions | default(omit) }}'
    dump: '{{ item.fs_dump | default(omit) }}'
    passno: '{{ item.fs_passno | default(omit) }}'
  loop: '{{ storage_conf }}'
  when:
    - item.fs_mountpoint is defined
    - item.fs_src is defined
  notify: systemd reload
  tags:
    - storage
    - mount

- name: "filesystem (xfs on buster)"
  command: 'xfs_growfs {{ item.fs_mountpoint }}'
  loop: '{{ storage_conf }}'
  when:
    - not ansible_check_mode
    - lv is changed
    - item.fs_mountpoint is defined
    - item.fs_type is defined
    - item.fs_type == 'xfs'
    - ansible_distribution_release in [ 'buster', 'sid' ]
  tags:
    - storage
    - fs
    - resize
